In [1]:
import pandas as pd
import numpy as np

In [6]:
train_df = pd.read_csv("../data/raw/train.csv", dtype={'StateHoliday': str})
stores_df = pd.read_csv("../data/raw/store.csv")

In [7]:
train_df

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,5,2015-07-31,5263,555,1,1,0,1
1,2,5,2015-07-31,6064,625,1,1,0,1
2,3,5,2015-07-31,8314,821,1,1,0,1
3,4,5,2015-07-31,13995,1498,1,1,0,1
4,5,5,2015-07-31,4822,559,1,1,0,1
...,...,...,...,...,...,...,...,...,...
1017204,1111,2,2013-01-01,0,0,0,0,a,1
1017205,1112,2,2013-01-01,0,0,0,0,a,1
1017206,1113,2,2013-01-01,0,0,0,0,a,1
1017207,1114,2,2013-01-01,0,0,0,0,a,1
1017208,1115,2,2013-01-01,0,0,0,0,a,1

In [8]:
train_df['StateHoliday'].apply(type).value_counts()

StateHoliday
<class 'str'>    1017209
Name: count, dtype: int64

In [9]:
train_df.shape

(1017209, 9)

In [10]:
stores_df.head()

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN

In [11]:
train_df.isna().sum()

Store            0
DayOfWeek        0
Date             0
Sales            0
Customers        0
Open             0
Promo            0
StateHoliday     0
SchoolHoliday    0
dtype: int64

In [12]:
stores_df.isna().sum()

Store                          0
StoreType                      0
Assortment                     0
CompetitionDistance            3
CompetitionOpenSinceMonth    354
CompetitionOpenSinceYear     354
Promo2                         0
Promo2SinceWeek              544
Promo2SinceYear              544
PromoInterval                544
dtype: int64

In [13]:
stores_df.shape

(1115, 10)

In [14]:
train_df['Date'].min()

'2013-01-01'

In [15]:
train_df['Date'].max()

'2015-07-31'

In [16]:
train_df.duplicated(subset=['Store','Date']).sum()

np.int64(0)

In [17]:
train_df['Store'].nunique()

1115

In [20]:
train_df[(train_df['Open'] == 1) & (train_df['Sales'] == 0)]

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
86825,971,5,2015-05-15,0,0,1,0,0,1
142278,674,4,2015-03-26,0,0,1,0,0,0
196938,699,4,2015-02-05,0,0,1,1,0,0
322053,708,3,2014-10-01,0,0,1,1,0,0
330176,357,1,2014-09-22,0,0,1,0,0,0
340348,227,4,2014-09-11,0,0,1,0,0,0
340860,835,4,2014-09-11,0,0,1,0,0,0
341795,835,3,2014-09-10,0,0,1,0,0,0
346232,548,5,2014-09-05,0,0,1,1,0,1
346734,28,4,2014-09-04,0,0,1,1,0,0
347669,28,3,2014-09-03,0,0,1,1,0,1
348604,28,2,2014-09-02,0,0,1,1,0,1
386065,102,4,2014-07-24,0,0,1,0,0,1
386173,238,4,2014-07-24,0,0,1,0,0,1
386227,303,4,2014-07-24,0,0,1,0,0,1
386304,387,4,2014-07-24,0,0,1,0,0,1
387652,882,3,2014-07-23,0,0,1,0,0,1
387656,887,3,2014-07-23,0,0,1,0,0,0
397285,102,6,2014-07-12,0,0,1,0,0,0
406384,925,4,2014-07-03,0,0,1,1,0,0
407532,57,2,2014-07-01,0,0,1,1,0,0
437311,1017,4,2014-06-05,0,0,1,1,0,0
438426,1017,3,2014-06-04,0,0,1,1,0,0
477534,1100,3,2014-04-30,0,0,1,1,0,0
478649,1100,2,2014-04-29,0,3,1,1,0,0
506085,661,5,2014-04-04,0,0,1,1,0,0
512964,850,6,2014-03-29,0,0,1,0,0,0
525365,986,2,2014-03-18,0,0,1,1,0,0
531396,327,3,2014-03-12,0,0,1,0,0,0
561199,25,4,2014-02-13,0,0,1,0,0,0
562314,25,3,2014-02-12,0,0,1,0,0,0
582982,623,6,2014-01-25,0,0,1,0,0,0
584097,623,5,2014-01-24,0,0,1,1,0,0
591147,983,6,2014-01-18,0,0,1,0,0,0
592262,983,5,2014-01-17,0,0,1,0,0,0
744697,663,1,2013-09-02,0,0,1,0,0,1
750000,391,3,2013-08-28,0,0,1,1,0,1
772836,927,4,2013-08-08,0,0,1,0,0,1
805283,1039,3,2013-07-10,0,0,1,0,0,0
806398,1039,2,2013-07-09,0,0,1,0,0,0
817174,665,6,2013-06-29,0,0,1,0,0,0
818289,665,5,2013-06-28,0,0,1,0,0,0
843969,700,3,2013-06-05,0,0,1,1,0,0
872940,681,5,2013-05-10,0,0,1,0,0,0
874853,364,3,2013-05-08,0,0,1,0,0,0
875968,364,2,2013-05-07,0,0,1,0,0,0
885113,589,1,2013-04-29,0,0,1,1,0,0
889932,948,4,2013-04-25,0,5,1,1,0,0
933937,353,6,2013-03-16,0,0,1,0,0,0
975098,259,4,2013-02-07,0,0,1,1,0,0
982983,339,4,2013-01-31,0,0,1,0,0,0
984098,339,3,2013-01-30,0,0,1,0,0,0
990681,232,4,2013-01-24,0,0,1,1,0,0
999016,762,4,2013-01-17,0,0,1,0,0,0

In [21]:
train_df.groupby('Store').size().nunique()

3

In [22]:
train_df.groupby('Store').size().value_counts()

942    934
758    180
941      1
Name: count, dtype: int64

In [23]:
train_df[train_df['Store']==942]

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
941,942,5,2015-07-31,8518,598,1,1,0,1
2056,942,4,2015-07-30,7311,496,1,1,0,1
3171,942,3,2015-07-29,6914,468,1,1,0,1
4286,942,2,2015-07-28,7754,487,1,1,0,1
5401,942,1,2015-07-27,9841,578,1,1,0,1
...,...,...,...,...,...,...,...,...,...
1012576,942,6,2013-01-05,5216,429,1,0,0,1
1013691,942,5,2013-01-04,5604,456,1,0,0,1
1014806,942,4,2013-01-03,4682,392,1,0,0,1
1015921,942,3,2013-01-02,3941,346,1,0,0,1
1017036,942,2,2013-01-01,0,0,0,0,a,1

In [24]:
weird = train_df[(train_df['Open'] == 1) & (train_df['Sales'] == 0)]
weird.shape[0]
weird.groupby('Store').size().sort_values(ascending=False)
weird['Customers'].describe()

count    54.000000
mean      0.148148
std       0.786859
min       0.000000
25%       0.000000
50%       0.000000
75%       0.000000
max       5.000000
Name: Customers, dtype: float64

In [28]:
counts = train_df.groupby('Store').size()
short_stores = counts[counts == 758]
short_stores.head()

Store
13    758
20    758
22    758
32    758
36    758
dtype: int64

In [33]:
subset = train_df[train_df['Store'] == 22].sort_values('Date')
print(subset['Date'].min())
print(subset['Date'].max())

2013-01-01
2015-07-31